package com.mycompany.proyectofinal.Vista;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JPanel;

public class GUITablero extends javax.swing.JFrame {

    private PanelControles panelControles;
    private PanelTablero panelTablero;

    public GUITablero(ActionListener controlador) throws IOException {
        initComponents();

        this.panelControles = new PanelControles(controlador);
        this.panelTablero = new PanelTablero();
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());

        this.add(this.panelTablero, BorderLayout.WEST);
        this.add(this.panelControles, BorderLayout.EAST);
    }

    public PanelControles getBotonesPanel() {
        return panelControles;
    }

    public PanelTablero getPanelTablero() {
        return panelTablero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
