package com.mycompany.proyectofinal.Vista;

import com.mycompany.proyectofinal.Modelo.Casilla;
import com.mycompany.proyectofinal.Modelo.Tablero;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;

public class PanelTablero extends javax.swing.JPanel {

    private Tablero tablero;
    private Image imagenFondo;

    public PanelTablero() throws IOException {
        this.tablero = new Tablero();
        setPreferredSize(new Dimension(768, 768));
        setFocusable(true);
        imagenFondo = ImageIO.read(getClass().getResourceAsStream("/tablero.png"));

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        g2.drawImage(imagenFondo, 0, 0, 768, 768, this);

        g2.setColor(Color.RED);
        g2.setStroke(new BasicStroke(2));

        for (int i = 0; i < tablero.getCasillas().size(); i++) {
            Casilla c = tablero.getCasillas().get(i);
            g2.drawRect(c.getX(), c.getY(), c.getAncho(), c.getAlto());
        }

    }

    public Tablero getTablero() {
        return tablero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
